name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull and deploy
        run: |
          cd ~/FastAPI
          git pull origin main
          docker build -t carewave-fastapi .
          docker stop carewave-container || true
          docker rm carewave-container || true
          docker run -d --name carewave-container -p 8000:8000 -p 5005:5005/udp --restart unless-stopped carewave-fastapi
          docker image prune -f
